name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "Have a nice Day!!"
      - name: Print goodbye
        run: |
            echo "Done - bye!"
            echo "see ya>"
